travis:
  secure:
    BINSTAR_TOKEN: P0kUcwWjDYNt4H39PFhfPsazAZkXGjQCMMJfRAkbfmajK16S5rAZGM7Op3gCRcihlWZ2+fAkF8qAKm9/7F7nzI9Fkjoug+JIMcEJJK70VmOg84aQPuPX3FoOLy9if5ywT4Od4K2rWWBUtizlNT7ZxDqJqty9ge43q6AT/1a4uoE9xfr8UzJWTkWxwGi+Y1O/Y+VZv2xhuZ1QORKyeSNaySS+7tMZks6iLrXXhAoZ7SkNhlJsK3rgo4knstg67FctLiHRvt6PiApziGBH/JNwYTAODebwffphDTo9DJeN0Wuv9Dl9jyF+fRmHcTKjCHIE7seCGxC2qmkhmCyPosVQ2zmfzRO1DaKnUze+3i3Dek4ZWEa9Q++UtLynKB8XbKTqoSpOddVprnyWnbY51aMNZM9M8HciHhySp+rb89jud9WaietNnBlOdg6G1IzFdDwKILjGFzbeWVv1qg8tpa/bS1iuJGOGEb6B0yw4EXemmP3OeEFzqw7r/sDsi9Do+iMGefxl5uYgahgKKSWjXl9t8T0W/nAmm+Ef//2JyJg4mr9eXxRpt8RLdRXL0YcU5LPiKkban2SRpwuVm8YzznPWlO+88STNzKd1EJHFtOWU+98k9e5TsiM6gddfqGQMJsAO8iDbVqy+Z5UMZTwmVsHWKBHyQvK/WAkd8TS5+jHbZ6M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
